/*
    I really don't know how fix :(

    https://submit.cs50.io/check50/a048a0cbbf0e8b8af8f81eaa95479de9c797c114

    Results for cs50/problems/2021/x/speller generated by check50 v3.3.9
    :) dictionary.c exists
    :) speller compiles
    :) handles most basic words properly
    :) handles min length (1-char) words
    :) handles max length (45-char) words
    :) handles words with apostrophes properly
    :) spell-checking is case-insensitive
    :) handles substrings properly
    :( program is free of memory errors
        expected "MISSPELLED WOR...", not "### unhandled ..."
*/

// Implements a dictionary's functionality

#include <strings.h>
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <stdbool.h>

#include "dictionary.h"

// Number of buckets in hash table
#define N 1

// Represents a node in a hash table
typedef struct node
{
    char word[LENGTH + 1];
    struct node *next;
}
node;

// Hash table
node *table[N];

// Returns true if word is in dictionary, else false
bool check(const char *word)
{
    // HASH THE WORD TO GET INDEX
    int index = hash(word);

    // TRAVERSE LINKED LIST AT THE CALCULATED INDEX
    for (node *cursor = table[index]; cursor != NULL; cursor = cursor->next)
    {
        // CMP WOWRD W/ DICT WORD (CASE-INSENSITIVE)
        if (strcasecmp(cursor->word, word) == 0)
        {
            // WORD FOUND
            return true;
        }
    }

    // WORD NOT FOUND
    return false;
}

// Hashes word to a number
unsigned int hash(const char *word)
{
    // SUM OF ASCII VALUES OF CHARACTERS
    unsigned int hash_value = 0;
    for (int i = 0; word[i] != '\0'; i++)
    {
        hash_value += tolower(word[i]);
    }

    // MOD(N) TO ENSURE IT FITS HASH TABLE SIZE
    return hash_value % N;
}

// Loads dictionary into memory, returning true if successful, else false
bool load(const char *dictionary)
{
    // OPEN DICT FILE
    FILE *file = fopen(dictionary, "r");
    if (file == NULL)
    {
        return false;
    }

    // READ WORDS FROM FILE AND INSERT INTO HASH TABLE
    char word[LENGTH + 1];
    while (fscanf(file, "%s", word) != EOF)
    {
        // ALLOC MEM FOR NEW NODE
        node *new_node = malloc(sizeof(node));
        if (new_node == NULL)
        {
            fclose(file);
            return false;
        }

        // COPY WORD IN NEW NODE
        strcpy(new_node->word, word);

        // HASH WORD TO GET INDEX
        int index = hash(word);

        // INSERT NEW NOTE AT BEG OF LINKED LIST
        new_node->next = table[index];
        table[index] = new_node;
    }

    // CLOSE DICT FILE
    fclose(file);

    return true;
}

// Returns number of words in dictionary if loaded, else 0 if not yet loaded
unsigned int size(void)
{
    unsigned int word_count = 0;

    // ITERATE THROUGH EACH BUCKET IN THE HASH TABLE
    for (int i = 0; i < N; i++)
    {
        // TRAVERSE LINKED LIST AT CURRENT INDEX
        for (node *cursor = table[i]; cursor != NULL; cursor = cursor->next)
        {
            word_count++;
        }
    }

    return word_count;
}

// Unloads dictionary from memory, returning true if successful, else false
bool unload(void)
{
    // ITERATE THROUGH EACH BUCKET IN THE HASH TABLE
    for (int i = 0; i < N; i++)
    {
        // TRAVERSE LINKED LIST AT CURRENT INDEX
        while (table[i] != NULL)
        {
            // KEEP REFERENCE TO CURRENT NODE
            node *cursor = table[i];

            // MOVE TO THE NEXT NODE IN THE LIST
            table[i] = cursor->next;

            // FREE MEM AT CURRENT NODE
            free(cursor);
        }
    }

    return true;
}
